title: O Novo Alhandrense
description: Um estúdio em Alhandra.
author: Michael T. H. Scott
theme: minima
url: "https://onovoalhandrense.art"
baseurl: ""collections:
  Caderno-de-esbocos:
    output: true
  Caderno-diario:
    output: true
  Moleskine:
    output: true
  Pastel-a-oleo:
    output: true
  Pinturas:
    output: true
  Helder:
    output: true
  Os-Destemidos:
    output: true
  Os-Dragoes:
    output: true
